owner: zeyxx
repo: upptime-gasdf

sites:
  - name: GASdf API
    url: https://asdfasdfa.tech/health
    expectedStatusCodes:
      - 200

  - name: GASdf Status
    url: https://asdfasdfa.tech/status
    expectedStatusCodes:
      - 200

  - name: HolDex API
    url: https://asdev-backend.onrender.com/api/health
    expectedStatusCodes:
      - 200

status-website:
  cname: status.asdfasdfa.tech
  logoUrl: https://asdfasdfa.tech/logo.png
  name: $ASDF Status
  theme: dark
  navbar:
    - title: Home
      href: https://asdfasdfa.tech
    - title: GitHub
      href: https://github.com/zeyxx/GASdf

workflowSchedule:
  uptime: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  staticSite: "0 0 * * *"
  summary: "0 0 * * *"

commitMessages:
  commitAuthorName: Upptime Bot
  commitAuthorEmail: upptime@asdfasdfa.tech
